name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
            - "6003:6003"
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - app-network

volumes:
    mysql_data:
    redis_data:

networks:
    app-network:
        driver: bridge
